services:
  fibergen:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true        # Docker run -t
    privileged: true
    network_mode: "host"
    volumes: # Mount relevant folders into container
      - ../.:/code/fibergen
